I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 127, in script
    menu:
KeyError: u'name'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 127, in script
    menu:
  File "C:\Users\fluff\Downloads\renpy-6.99.14-sdk\renpy\ast.py", line 1501, in execute
    renpy.exports.say(None, "\n".join(narration), interact=False)
  File "C:\Users\fluff\Downloads\renpy-6.99.14-sdk\renpy\exports.py", line 1175, in say
    who(what, *args, **kwargs)
  File "C:\Users\fluff\Downloads\renpy-6.99.14-sdk\renpy\character.py", line 1000, in __call__
    what = what_pattern.replace("[what]", sub(what, translate=translate))
  File "C:\Users\fluff\Downloads\renpy-6.99.14-sdk\renpy\character.py", line 982, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "C:\Users\fluff\Downloads\renpy-6.99.14-sdk\renpy\substitutions.py", line 242, in substitute
    s = formatter.vformat(s, (), kwargs)
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 563, in vformat
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 585, in _vformat
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 646, in get_field
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 605, in get_value
KeyError: u'name'

Windows-8-6.2.9200
Ren'Py 6.99.14.3135
CreatureCollege 1.0
